var wit = {
  "Data Safety:General": "You can share my data with Alice and Bob, but not Mallory or Trudy!",
  "Plugins:Norton 360": "You're plugged in to the matrix",
  "Plugins:Checkpoint Zonealarm": "You're plugged in to the matrix",
  "Plugins:Totem": "You're plugged in to the matrix",
  "Plugins:Viewpoint Media Player": "You're plugged in to the matrix",
  "Plugins:Google Talk": "You're plugged in to the matrix",
  "Plugins:DivX": "You're plugged in to the matrix",
  "Plugins:McAfee AV": "You're plugged in to the matrix",
  "Plugins:VeohTV (Veoh)": "You're plugged in to the matrix",
  "Plugins:Panda AV": "You're plugged in to the matrix",
  "Plugins:NSPluginWrapper": "You're plugged in to the matrix",
  "Plugins:Java (IcedTea)": "You're plugged in to the matrix",
  "Plugins:Comodo Firewall": "You're plugged in to the matrix",
  "Plugins:Quake Live": "You're plugged in to the matrix",
  "Plugins:Java (Java Embedding Plugin)": "You're plugged in to the matrix",
  "Plugins:ESET Smart Security": "You're plugged in to the matrix",
  "Plugins:Windows Media Player (Microsoft)": "You're plugged in to the matrix",
  "Plugins:Shockwave (Adobe)": "You're plugged in to the matrix",
  "Plugins:PDF (FoxIt)": "You're plugged in to the matrix",
  "Plugins:Citrix": "You're plugged in to the matrix",
  "Plugins:Plugger": "You're plugged in to the matrix",
  "Plugins:AIR (Adobe)": "You're plugged in to the matrix",
  "Plugins:Flash (swfdec)": "You're plugged in to the matrix",
  "Plugins:Kaspersky AV": "You're plugged in to the matrix",
  "Plugins:.NET (Microsoft)": "You're plugged in to the matrix",
  "Plugins:Trend Micro AV": "You're plugged in to the matrix",
  "Plugins:Avast AV": "You're plugged in to the matrix",
  "Plugins:Flash (Gnash)": "You're plugged in to the matrix",
  "Plugins:Norton AV": "You're plugged in to the matrix",
  "Plugins:Java (Sun)": "Write once. Plugin anywhere.",
  "Plugins:MSE AV": "You're plugged in to the matrix",
  "Plugins:VLC (VideoLAN)": "You're plugged in to the matrix",
  "Plugins:Java (Apple)": "You're plugged in to the matrix",
  "Plugins:Symantec AV": "You're plugged in to the matrix",
  "Plugins:Silverlight (Microsoft)": "You're plugged in to the matrix",
  "Plugins:F-Secure AV": "You're plugged in to the matrix",
  "Plugins:Flash (Adobe)": "Ah, you like dealing with stable, secure, bug-free plugins",
  "Plugins:Other": "You're plugged in to the matrix",
  "Plugins:Xine": "You're plugged in to the matrix",
  "Plugins:AVG AV": "You're plugged in to the matrix",
  "Plugins:Comodo AV": "You're plugged in to the matrix",
  "Plugins:Nvidia ActiveArmor": "You're plugged in to the matrix",
  "Plugins:Symantec Endpoint Protection": "You're plugged in to the matrix",
  "Plugins:RealPlayer (Real)": "You're plugged in to the matrix",
  "Plugins:QuickTime (Apple)": "Just don't put round corners on this plugin. You'll be sued.",
  "Plugins:PDF (Adobe)": "Ah, you like dealing with stable, secure, bug-free plugins",
  "Plugins:JInitiator": "You're plugged in to the matrix",
  "Plugins:Norton Confidential": "You're plugged in to the matrix",
  "Plugins:Java (Oracle)": "Write once. Plugin anywhere.",
  "Plugins:Silverlight (Mono)": "You're plugged in to the matrix",
  "Plugins:ESET NOD32 AV": "You're plugged in to the matrix",
  "Plugins:Windows Media Player (Flip4Mac)": "You're plugged in to the matrix",
  "Plugins:Mplayer": "You're plugged in to the matrix",
  "Servo:Rust": "No metal decay here - it's shiny and new!",
  "MailNews Core Graveyard:Palm Sync": "You're favourite component is in the palm of my hand",
  "Testing:Reftest": "Spot the difference",
  "Testing:Mozbase": "All your testing belong to us",
  "Testing:GoFaster": "You feel the need for speed",
  "Testing:XPCShell Harness": "When a JS shell isn't enough...",
  "Testing:Eideticker": "Is this component in your photographic memory?",
  "Testing:ManifestParser": "One manifest to rule them all",
  "Testing:New Frameworks": "TEST_UNEXPECTED_FAIL!",
  "Testing:Mozmill": "These tests aren't exactly run of the mill",
  "Testing:Mochitest Chrome": "TEST_UNEXPECTED_FAIL!",
  "Testing:Mochitest": "TEST_UNEXPECTED_FAIL!",
  "Testing:Orange Factor": "I think I know your favourite colour...",
  "Testing:BrowserTest": "TEST_UNEXPECTED_FAIL!",
  "Testing:ssltunnel": "Schneier would be proud",
  "Testing:Peptest": "Pep up! This browser seems reponsive!",
  "Testing:httpd.js": "404 Not Found",
  "Testing:ProfileManager": "This component keeps a low profile...",
  "Testing:Minotaur": "I'm feeling bullish about our partner builds",
  "Testing:Sisyphus": "About to crash your browser so you can reproduce...",
  "Testing:Autophone": "Tegra-wrangler",
  "Testing:Infrastructure": "Re-imaging the entire build pool...",
  "Testing:General": "TEST_UNEXPECTED_FAIL!",
  "Testing:WebQA": "mozilla.org WFM",
  "Testing:Talos": "Crunching the numbers...",
  "Testing:Code Coverage": "Taking every branch...",
  "Testing:Fennec Profile Tool": "Keeping a low profile...",
  "Testing:Autolog": "TEST_UNEXPECTED_FAIL!",
  "Testing:SUTAgent": "Reconnecting socket...",
  "Testing:Marionette": "Pulling the strings of Gaia and B2G...",
  "Testing:TPS": "I feel like we're in sync...",
  "Untriaged Bugs:General": "",
  "Untriaged Bugs:Firefox": "",
  "Untriaged Bugs:Fennec": "",
  "Mozilla Messaging:Security": "Schneier would be proud",
  "Mozilla Messaging:Try Server": "If at first you don't succeed...",
  "Mozilla Messaging:Office": "The office needs more gadgets!",
  "Mozilla Messaging:ispdb": "Auto-configuration FTW",
  "Mozilla Messaging:Server Operations": "Have those pesky comm-central devs borked hg again?",
  "Mozilla Messaging:Release Engineering": "Ship it!",
  "Mozilla Messaging:AUS Server": "Keep those trains running...",
  "Websites Graveyard:mozillaservice.org": "How can I serve you?",
  "Websites Graveyard:www.schooloffirefox.com": "School's out!",
  "Websites Graveyard:opentochoice.org": "Vote Firefox!",
  "Websites Graveyard:irc.mozilla.org": "/join #developers",
  "Websites Graveyard:spreadfirefox.com": "Spread the word!",
  "Websites Graveyard:jetpackgallery.mozillalabs.com": "Switching off the jetpack...",
  "Websites Graveyard:firefoxlive.mozilla.org": "Red pandas on cam!",
  "Other Applications:Venkman JS Debugger": "Setting breakpoint...",
  "Other Applications:McCoy": "I'm a doctor, not a miracle worker!",
  "Other Applications:Fizzypop": "Watch your step on that scaffolding!",
  "Other Applications:Narcissus": "javascriptInterpreter.prototype = ...",
  "Other Applications:XUL Explorer": "Who ya gonna call?",
  "Other Applications:bzexport": "r+",
  "Other Applications:QA Companion": "The Litmus tester's BFF",
  "Other Applications:CCK": "Suck it nerds - I'm going corporate!",
  "Other Applications:mozStorage Explorer": "DROP ALL TABLES;",
  "Other Applications:Reporter": "You'd better not report this page as a broken website!",
  "Other Applications:ChatZilla": "/join #developers",
  "Other Applications:PyXPCOM": "def nsISupports",
  "Other Applications:qimportbz": "hg resolved fixed",
  "Other Applications:DOM Inspector": "Take a peek behind the scenes...",
  "Mozilla QA:MozTrap": "It's a trap!",
  "Mozilla QA:Infrastructure": "Re-imaging all QA machines...",
  "Mozilla QA:Case Conductor-Platform": "Picking up the conductor's baton...",
  "Mozilla QA:General": "Well, if this page crashes Firefox, I'm in good hands...",
  "Mozilla QA:Mozmill Automation": "These tests aren't run of the mill!",
  "Mozilla QA:Mozmill Tests": "These tests aren't run of the mill!",
  "mozilla.org:Video": "Moving picture show...",
  "mozilla.org:Governance": "Organising the rabble...",
  "mozilla.org:Server Operations: Netops": "Bit-wrangler...",
  "mozilla.org:Release Engineering: Releases": "Ship it!",
  "mozilla.org:Miscellaneous": "Home of the red panda!",
  "mozilla.org:Release Engineering: Developer Tools": "Let's use BuildAPI to cancel all the builds!",
  "mozilla.org:Server Operations: RelEng": "Currently re-imaging all machines in the VPN...",
  "mozilla.org:Security Assurance: Operations": "The first line of defence",
  "mozilla.org:Talkback Server & Webtool": "You talking to me?",
  "mozilla.org:Security Assurance: Applications": "The first line of defence",
  "mozilla.org:CVS: Copy": "The 80s called. They want their VCS back.",
  "mozilla.org:Release Engineering: Custom Builds": "Howdy, partner!",
  "mozilla.org:Localization Server": "You help put the 'world' in world-wide web. Awesome.",
  "mozilla.org:Server Operations: Developer Services": "Did those pesky devs break hg again?",
  "mozilla.org:Test Tracker": "TEST_UNEXPECTED_FAIL!",
  "mozilla.org:Security Assurance: Incident": "The first line of defence",
  "mozilla.org:Discussion Forums": "Don't feed the trolls...",
  "mozilla.org:MozillaBuild": "Helping Windows users towards a sane build environment...",
  "mozilla.org:Server Operations: Virtualization": "Puppet master",
  "mozilla.org:FTP: Mirrors": "Mirror mirror on the wall, which server is geographically closest of them all?",
  "mozilla.org:CA Certificates": "Don't mention DigiNotar!",
  "mozilla.org:Hg: Customizations": "Loading pushlog...",
  "mozilla.org:Server Operations: Labs": "Bit-wrangler...",
  "mozilla.org:Release Engineering": "Ship it!",
  "mozilla.org:Release Engineering: Automation (Release Automation)": "Ship it!",
  "mozilla.org:Release Engineering: Machine Management": "So, who loves Tegras?",
  "mozilla.org:Repository Account Requests": "I can haz commit access?",
  "mozilla.org:Tinderbox Configuration": "",
  "mozilla.org:Release Engineering: Automation (General)": "Build it and they will come...",
  "mozilla.org:Server Operations: Desktop Issues": "I can haz gadgets?",
  "mozilla.org:Server Operations: Storage": "Needs more 3.5 inch floppies...",
  "mozilla.org:Server Operations: Web Operations": "Updating all mozilla.org production pages to their 1999 versions",
  "mozilla.org:Server Operations: DCOps": "Powering down all data centres...",
  "mozilla.org:Security Assurance": "The first line of defence",
  "mozilla.org:Server Operations: Database": "DROP TABLE servertypes;",
  "mozilla.org:Server Operations: AMO Operations": "So many extensions...",
  "mozilla.org:Webdev": "Entering quirks mode...",
  "mozilla.org:Licensing": "You need to sign a NDA before you see the code...",
  "mozilla.org:Server Operations: Telecom": "Hey, I just met you, and this is crazy, but here's my Asterisk config, VoIP me maybe?",
  "mozilla.org:Security Assurance: Review Request": "What? Displaying a user's password in large blinking text is a bad idea?!?",
  "mozilla.org:FTP: Staging": "ZOMG. New version of Firefox leaks early!!",
  "mozilla.org:Server Operations: ACL Request": "Port in a storm",
  "mozilla.org:Server Operations: Infrastructure": "Powering down all data centres...",
  "mozilla.org:Community Giving": "It's all about community...",
  "mozilla.org:Server Operations: Projects": "Bit-wrangler...",
  "mozilla.org:CVS: Administration": "The 80s called. They want their VCS back.",
  "mozilla.org:Relic": "I prefer 'antique'",
  "mozilla.org:Server Operations": "She cannae take it anymore, captain!",
  "mozilla.org:Server Operations: Account Requests": "I can haz access all areas?",
  "mozilla.org:Project Review": "r+",
  "mozilla.org:Release Engineering: Platform Support": "What do we need Windows builds for anyway?",
  "Directory:PerLDAP": "",
  "Directory:LDAP XPCOM SDK": "",
  "Directory:LDAP Java SDK": "",
  "Directory:LDAP Tools": "",
  "Directory:LDAP C SDK": "",
  "Camino:History": "Those who can't remember the past...",
  "Camino:OS Integration": "You've went native",
  "Camino:Page Layout": "You've went native",
  "Camino:Printing": "PC LOAD LETTER",
  "Camino:Plug-ins": "Additional plugins are required to view this content...",
  "Camino:Preferences": "This might void your warranty...",
  "Camino:Security": "You've went native",
  "Camino:Product Site": "You've went native",
  "Camino:Tabbed Browsing": "You've went native",
  "Camino:General": "You've went native",
  "Camino:Accessibility": "You've went native",
  "Camino:Annoyance Blocking": "You've went native",
  "Camino:HTML Form Controls": "You've went native",
  "Camino:Downloading": "You've went native",
  "Camino:Toolbars & Menus": "You've went native",
  "Camino:Translations": "You've went native",
  "Camino:Drag & Drop": "You've went native",
  "Camino:Bookmarks": "You've went native",
  "Camino:Location Bar & Autocomplete": "Remember when we had to type the same things over and over, like primitive beasts?",
  "Firefox for Metro:Components": "Charming!",
  "Firefox for Metro:Browser": "Big colourful rectangles are the future",
  "Firefox for Metro:General": "Big colourful rectangles are the future",
  "Firefox for Metro:Shell": "Charming!",
  "Firefox for Metro:Input": "Tap tap!",
  "Firefox for Metro:File Handling": "I'm going to mime the name of your top component",
  "Firefox for Metro:Build Config": "Making make do your bidding",
  "Firefox for Metro:Theme": "Big colourful rectangles are the future",
  "Toolkit Graveyard:Data Collection/Metrics": "Ah, retro Mozilla. You hipster.",
  "Other Applications Graveyard:Nightly Tester Tools": "Making dogfood more appetizing...",
  "Air Mozilla:History": "From Mountain View to the world...",
  "Air Mozilla:Rendering": "From Mountain View to the world...",
  "Air Mozilla:Other": "From Mountain View to the world...",
  "Air Mozilla:Community": "From Mountain View to the world...",
  "Air Mozilla:Extron": "From Mountain View to the world...",
  "Air Mozilla:Streaming": "From Mountain View to the world...",
  "Air Mozilla:DAM": "From Mountain View to the world...",
  "Air Mozilla:Vidyo": "From Mountain View to the world...",
  "Air Mozilla:Hardware": "From Mountain View to the world...",
  "Air Mozilla:BigBlueButton": "From Mountain View to the world...",
  "Air Mozilla:Crestron": "From Mountain View to the world...",
  "Air Mozilla:Mobile": "From Mountain View to the world...",
  "Air Mozilla:Venues": "From Mountain View to the world...",
  "Air Mozilla:Events": "From Mountain View to the world...",
  "Air Mozilla:iCal": "From Mountain View to the world...",
  "Air Mozilla:Content": "From Mountain View to the world...",
  "Air Mozilla:Schedule": "From Mountain View to the world...",
  "bugzilla.mozilla.org:Extensions: Needinfo": "Here's the info on your favourite component",
  "bugzilla.mozilla.org:Extensions: FlagTypeComment": "approval-firefox1.0+",
  "bugzilla.mozilla.org:Bugzilla Tweaks": "Rock your Firefox? Pfft. Pimp my Bugzilla is where it's at!",
  "bugzilla.mozilla.org:Extensions: REST": "Hey, this page uses Bugzilla's REST API. How meta",
  "bugzilla.mozilla.org:Extensions: Push": "Finger on the pulse",
  "bugzilla.mozilla.org:API": "Hey, this page uses Bugzilla's API. How meta",
  "bugzilla.mozilla.org:Extensions: Component Watching": "I'm watching you",
  "bugzilla.mozilla.org:Administration": "Resolve all the bugs!",
  "bugzilla.mozilla.org:Extensions: Other": "Needs a bug-fixing extension",
  "bugzilla.mozilla.org:Extensions: Inline History": "Assignee: nobody@mozilla.org → firebot",
  "bugzilla.mozilla.org:Extensions: TryAutoLand": "Taking the hard work out of turning the tree orange",
  "bugzilla.mozilla.org:Extensions: BrowserID": "You have a bug-fixing persona",
  "bugzilla.mozilla.org:Extensions: OrangeFactor": "What's your favourite colour?",
  "bugzilla.mozilla.org:Extensions: Tracking Flags": "status-firebird0.7: affected",
  "bugzilla.mozilla.org:Extensions: REMO": "Represent!",
  "bugzilla.mozilla.org:General": "Close all the bugs!",
  "bugzilla.mozilla.org:Extensions: MozProjectReview": "r+",
  "bugzilla.mozilla.org:Extensions: BMO": "Who do I speak to about swinging the next BMO sweepstake?",
  "bugzilla.mozilla.org:User Interface": "Mid-air collision detected!",
  "bugzilla.mozilla.org:Extensions: SecureMail": "Schneier would be proud",
  "bugzilla.mozilla.org:Extensions: GuidedBugEntry": "So many fields!",
  "bugzilla.mozilla.org:Extensions: Splinter": "r+",
  "Firefox Affiliates:Social Integration": "Spread the word!",
  "Firefox Affiliates:affiliates.mozilla.org banners": "Spread the word!",
  "Firefox Affiliates:affiliates.mozilla.org": "Spread the word!",
  "Datazilla:Database": "DROP TABLE objectstore;",
  "Datazilla:Web service": "Let's crunch some numbers",
  "Datazilla:User interface": "Let's crunch some numbers",
  "Datazilla:Client": "Let's crunch some numbers",
  "Datazilla:Metrics": "Let's crunch some numbers",
  "support.mozilla.org:Localization": "You help put the 'world' in world-wide web. Awesome.",
  "support.mozilla.org:Knowledge Base Software": "Know-it-all!",
  "support.mozilla.org:Forum": "Don't feed the trolls...",
  "support.mozilla.org:General": "Help!",
  "support.mozilla.org:Army of Awesome": "Reporting for duty, sergeant",
  "support.mozilla.org:Mobile": "Will Fx run on my 1998 Nokia 5110?",
  "support.mozilla.org:Chat": "A/S/L/Browser?",
  "support.mozilla.org:Knowledge Base Articles": "Know-it-all!",
  "support.mozilla.org:Search": "Have you found what you're looking for",
  "support.mozilla.org:Users and Groups": "Superheroes here!",
  "support.mozilla.org:Questions": "You've got questions? We've got answers!",
  "support.mozilla.org:Code Quality": "A+. Would use again.",
  "Mozilla Services:Android: Firefox Account": "I feel like we're in sync",
  "Mozilla Services:Operations: Hardware": "Re-imaging all servers with user sync data...",
  "Mozilla Services:Metrics and Firefox Health Report": "I'm giving you a clean bill of health",
  "Mozilla Services:Share: Web Client": "It's good to share",
  "Mozilla Services:Server: Product Announcements Redirector": "Here's an interesting snippet...",
  "Mozilla Services:Server: Product Announcements Campaign Manager": "Here's an interesting snippet...",
  "Mozilla Services:Server: Identity": "No-one need ever be a persona non grata with your great work",
  "Mozilla Services:Server: Account Portal": "Now you're thinking in Portals...",
  "Mozilla Services:Firefox Sync: Crypto": "Schneier would be proud",
  "Mozilla Services:Firefox Sync: Build": "I feel like we're in sync",
  "Mozilla Services:Firefox Sync: Backend": "I feel like we're in sync",
  "Mozilla Services:Server: Token": "Schneier would be proud",
  "Mozilla Services:Android: Product Announcements": "Here's an interesting snippet...",
  "Mozilla Services:Server: Core": "rm -rf allsyncdata/",
  "Mozilla Services:Notifications": "Ping!",
  "Mozilla Services:Firefox Sync: Other Clients": "I feel like we're in sync",
  "Mozilla Services:Operations: Deployment Requests": "Ship it!",
  "Mozilla Services:Firefox Home": "Bookmarks. With patented rounded corners.",
  "Mozilla Services:Android Sync": "I feel like we're in sync",
  "Mozilla Services:Firefox: Common": "I feel like we're in sync",
  "Mozilla Services:Server: Key Exchange": "Schneier would be proud",
  "Mozilla Services:General": "I feel like we're in sync",
  "Mozilla Services:Server: Share": "It's good to share",
  "Mozilla Services:Server: Other": "rm -rf allsyncdata/",
  "Mozilla Services:Web Site": "I feel like we're in sync",
  "Mozilla Services:Operations: Metrics/Monitoring": "Let's crunch some numbers...",
  "Mozilla Services:Firefox Sync: UI": "I feel like we're in sync",
  "Mozilla Services:Server: Sync": "I feel like we're in sync",
  "Mozilla Services:Share: Firefox Client": "It's good to share",
  "Mozilla Services:Server: Registration": "Pro-tip: store passwords in clear text",
  "Mozilla Services:Operations": "She cannae take it anymore, captain!",
  "Bugzilla:User Accounts": "nobody@mozilla.org sure must get a lot of bugmail!",
  "Bugzilla:Administration": "Resolve all the bugs!",
  "Bugzilla:Testing Suite": "If these tests fail, do you file in Bugzilla? How meta.",
  "Bugzilla:Bugzilla-General": "It's a feature",
  "Bugzilla:Dependency Views": "You're blocking me",
  "Bugzilla:WebService": "I REST my case",
  "Bugzilla:Extensions": "Enhancement request: a bug-fixing extension",
  "Bugzilla:Email Notifications": "Mid-air collision detected!",
  "Bugzilla:Bug Import/Export & Moving": "Let's track our bugs in Excel!",
  "Bugzilla:Database": "DROP TABLE bugs;",
  "Bugzilla:Documentation": "RTFM",
  "Bugzilla:Whining": "I can haz review?",
  "Bugzilla:bugzilla.org": "Please wait while your bugs are retreived...",
  "Bugzilla:User Interface": "Mid-air collision detected!",
  "Bugzilla:Reporting/Charting": "Who did what, when, and to whom?",
  "Bugzilla:Attachments & Requests": "r?",
  "Bugzilla:Incoming Email": "You need my bank details to move $10 million from a dormant account? Sounds like a legitimate bug!",
  "Bugzilla:Creating/Changing Bugs": "Mid-air collision detected!",
  "Bugzilla:QA Test Scripts": "If these tests fail, do you file in Bugzilla? How meta.",
  "Bugzilla:Installation & Upgrading": "Pfft. It refuses to install on my ZX Spectrum",
  "Bugzilla:Query/Bug List": "Please wait while your bugs are retreived...",
  "Firefox:Tabbed Browser": "You're a red panda master",
  "Firefox:Panorama": "You're an enabler. You're helping tab junkies everywhere get their fix!",
  "Firefox:Developer Tools: Source Editor": "Hunting for a good editor...",
  "Firefox:Location Bar": "Remember when we actually had to remember URLs we'd previously typed? Ugh.",
  "Firefox:File Handling": "I'm going to mime the name of your top component",
  "Firefox:Theme": "Does it come in black?!?",
  "Firefox:Keyboard Navigation": "No mice infestation here",
  "Firefox:Session Restore": "Well, this is embarrassing...",
  "Firefox:Developer Tools": "Firebug shmirebug",
  "Firefox:Security": "Larry's watching you",
  "Firefox:SocialAPI": "I think I should post on your wall about your component of choice!",
  "Firefox:Disability Access": "Making the web open to everyone. Awesome.",
  "Firefox:General": "You're a red panda master",
  "Firefox:PDF Viewer": "Plugins? We don't need no stinking plugins!",
  "Firefox:Developer Tools: Style Editor": "display: none;",
  "Firefox:Downloads Panel": "I'm downloading more RAM right now...",
  "Firefox:Help Documentation": "RTFM",
  "Firefox:Web Apps": "The web is the platform. And you're building the platform.",
  "Firefox:Build Config": "Making make do your bidding",
  "Firefox:Extension Compatibility": "&lt;em:maxVersion&gt;1.0.&lt;/em:maxVersion&gt;",
  "Firefox:Private Browsing": "You're not finding out what's in my browser history...",
  "Firefox:Untriaged": "",
  "Firefox:Microsummaries": "Splitting the atom",
  "Firefox:Bookmarks & History": "Those who can't remember the past...",
  "Firefox:Webapp Runtime": "The web is the platform. And you're building the platform.",
  "Firefox:Developer Tools: Inspector": "Take a peek behind the scenes...",
  "Firefox:Phishing Protection": "Seems phishy",
  "Firefox:Search": "Have you found what you're looking for?",
  "Firefox:SocialAPI: Providers": "You should post about this on your wall.",
  "Firefox:Page Info": "Take a peek behind the scenes...",
  "Firefox:RSS Discovery and Preview": "Splitting the atom",
  "Firefox:Preferences": "This might void your warranty...",
  "Firefox:Shell Integration": "Do you want to make Netscape 6 your default browser?",
  "Firefox:Installer": "Firefox will start in just a few moments...",
  "Firefox:Migration": "TODO: Delete their copies of IE and Chrome after you've migrated their data",
  "Firefox:Toolbars": "Needs more buttons.",
  "Firefox:Menus": "On the menu: awesomeness",
  "Firefox:Developer Tools: Debugger": "Setting breakpoint...",
  "Firefox:Developer Tools: Console": "Firebug shmirebug",
  "Firefox:Developer Tools: Scratchpad": "Quick prototyping and testing FTW!",
  "Firefox:WinQual Reports": "",
  "NSPR:NSPR": "PR_FavouriteComponent...",
  "Minimo:General": "Where did I put my Pocket PC?",
  "Minimo:Device Specific": "Where did I put my Pocket PC?",
  "Minimo:Build Config": "Making make do your bidding",
  "Minimo:Minimo Front-End": "Where did I put my Pocket PC?",
  "addons.mozilla.org:Forums": "Let's talk about that extension...",
  "addons.mozilla.org:Plugins": "Additional plugins are required to view this content...",
  "addons.mozilla.org:Dictionaries": "Klingon dictionary required...",
  "addons.mozilla.org:Collections": "Jumping on the bandwagon...",
  "addons.mozilla.org:API": "Jumping on the bandwagon...",
  "addons.mozilla.org:Facebook Application": "Still rocking your Firefox...",
  "addons.mozilla.org:Administration": "Administering the extension of the Mozilla universe...",
  "addons.mozilla.org:Add-on Validation": "Firebird 0.6 is not a valid maxversion",
  "addons.mozilla.org:Search": "Have you found what you're looking for?",
  "addons.mozilla.org:Public Pages": "A world of extensions...",
  "addons.mozilla.org:Search Plugins": "Have you found what you're looking for?",
  "addons.mozilla.org:Compatibility Tools": "&lt;em:maxversion&lt;Firebird 0.6&lt;/em:maxversion&gt;",
  "addons.mozilla.org:Code Quality": "A+. Would use again!",
  "addons.mozilla.org:Statistics": "0 weekly downloads...",
  "addons.mozilla.org:Add-on Security": "Schneier would be proud",
  "addons.mozilla.org:Maintenance Scripts": "",
  "addons.mozilla.org:Localization": "You help put the 'world' in world-wide web. Awesome.",
  "addons.mozilla.org:Discovery Pane": "Up and coming...",
  "addons.mozilla.org:Policy": "Don't be evil",
  "addons.mozilla.org:Add-on Builder": "Igniting jetpack...",
  "addons.mozilla.org:Blocklisting": "You've been placed on the naughty list!",
  "addons.mozilla.org:Admin/Editor Tools": "r+",
  "addons.mozilla.org:Collector Extension": "Jumping on the bandwagon...",
  "addons.mozilla.org:Developer Pages": "RTFM",
  "Marketplace:Statistics": "0 weekly downloads...",
  "Marketplace:Admin Tools": "Administering a world of apps",
  "Marketplace:Security": "Schneier would be proud",
  "Marketplace:General": "Apps everywhere!",
  "Marketplace:Reviewer Tools": "r+",
  "Marketplace:API": "GET /api/apps/yourfavouritecomponent",
  "Marketplace:Validation": "Apps everywhere!",
  "Marketplace:Consumer Pages": "Apps everywhere!",
  "Marketplace:Search": "Have you found what you're looking for?",
  "Marketplace:Code Quality": "A+. Would use again!",
  "Marketplace:Developer Pages": "RTFM",
  "Marketplace:Payments/Refunds": "Do you accept Bitcoin?!?",
  "Input:Dashboard": "Dash it!",
  "Input:Sites": "Let me tell you how I feel...",
  "Input:General": "Let me tell you how I feel...",
  "Input:Frontend": "Let me tell you how I feel...",
  "Input:GrouperFish": "Let me tell you how I feel...",
  "Input:Submission": "Let me tell you how I feel...",
  "Input:Search": "Have you found what you're looking for?",
  "Input:Themes": "I'm detecting a theme...",
  "Input:Backend": "Let me tell you how I feel...",
  "Input:Code Quality": "A+. Would use again!",
  "Webtools:Doctor": "He's dead, Jim",
  "Webtools:Download Day": "Look at all that traffic!",
  "Webtools:ISPDB Database Entries": "",
  "Webtools:MXR": "View Source",
  "Webtools:Bouncer": "Mirror mirror on the wall, which server is geographically closest of them all?",
  "Webtools:Toolbox": "What's in your toolbox?",
  "Webtools:Pulse": "You've got your finger on it...",
  "Webtools:Hendrix": "All along the watchtower...",
  "Webtools:Mozbot": "Mmm. Botsnacks.",
  "Webtools:General": "",
  "Webtools:SSO": "One sign-on to rule them all",
  "Webtools:ISPDB Server": "",
  "Webtools:Tinderboxpushlog": "Stars everywhere!",
  "Webtools:Dragnet": "Fishing for DLLs",
  "Webtools:Litmus": "I think Firefox is alkaline",
  "Webtools:Bonsai": "Ah, an archaeologist...",
  "Webtools:Air Mozilla": "From Mountain View to the world...",
  "Webtools:Cesium": "y so slow?",
  "Webtools:Web Sniffer": "GET myfavouritecomponent",
  "Webtools:Tinderbox3": "What's your favourite colour? Green, orange or red?",
  "Webtools:TCM": "",
  "Webtools:Leeroy": "",
  "Webtools:Sheriff": "Stars everywhere!",
  "Webtools:Etherpad": "Let's collaborate",
  "Webtools:Elmo": "You help put the 'world' in world-wide web. Awesome.",
  "Webtools:Uninstall Survey": "Was it something I said?",
  "Webtools:Phonebook": "Hey, I just met you, this is crazy here's my number...",
  "Webtools:Webtest": "",
  "Webtools:BzAPI": "Hey, this page uses BzAPI. How meta.",
  "Webtools:Verbatim": "You help put the 'world' in world-wide web. Awesome.",
  "Webtools:Pontoon": "You help put the 'world' in world-wide web. Awesome.",
  "Webtools:Prior Art": "Don't feed the [patent] troll",
  "Webtools:Tinderbox": "What's your favourite colour? Green, orange or red?",
  "Webtools:Tree Status": "CLOSE ALL THE TREES!",
  "Webtools:Tinderbox2": "What's your favourite colour? Green, orange or red?",
  "Webtools:DXR": "View Source",
  "Webtools:Headrush": "Someone has ideas...",
  "Webtools:Graph Server": "Needs more pie charts...",
  "Webtools:Despot": "Remember CVS? Yeah, so do the NSS guys.",
  "Webtools:PTO": "PTO Request denied. Back to work, slacker.",
  "Webtools:Reporter": "I hope this isn't a broken website...",
  "Webtools:Kubla": "Django schmango",
  "Webtools:Narro": "",
  "Webtools:Domesday": "",
  "Webtools:Mozilla Community Sites": "A world of Mozillians...",
  "Boot2Gecko:Builds": "Ship it!",
  "Boot2Gecko:Hardware": "Fails to install on my 1998 Nokia 5110",
  "Boot2Gecko:General": "Scaling Kilmanjaro...",
  "Boot2Gecko:Gaia::E-Mail": "You've got mail...",
  "Boot2Gecko:Gaia::Homescreen": "Do you have Kilimanjaro as your wallpaper?",
  "Boot2Gecko:Gaia::Settings": "Scaling Kilmanjaro...",
  "Boot2Gecko:Gaia::Browser": "Scaling Kilmanjaro...",
  "Boot2Gecko:Gaia::Calendar": "Reminder: Ship FirefoxOS",
  "Boot2Gecko:Gaia": "iOs shmiOs.",
  "Boot2Gecko:Gaia::System": "Scaling Kilmanjaro...",
  "Firefox Graveyard:Account Manager": "Ah, retro Mozilla. You hipster.",
  "SeaMonkey:Tabbed Browser": "I'm keeping tabs on you...",
  "SeaMonkey:MailNews: General": "You've got mail...",
  "SeaMonkey:Passwords & Permissions": "Pro-tip: use 'password' as your password!",
  "SeaMonkey:Find In Page": "Have you found what you were looking for?",
  "SeaMonkey:Release Engineering": "Ship it!",
  "SeaMonkey:Location Bar": "Let's address this...",
  "SeaMonkey:OS Integration": "You've went native",
  "SeaMonkey:Bookmarks & History": "Those who can't remember the past...",
  "SeaMonkey:Download & File Handling": "I'm going to mime the name of your top component",
  "SeaMonkey:Search": "Have you found what you're looking for?",
  "SeaMonkey:Page Info": "Peek behind the curtains...",
  "SeaMonkey:Session Restore": "Well, this is embarrassing...",
  "SeaMonkey:Sidebar": "Can I take you aside?",
  "SeaMonkey:Composer": "document.execcommand('insertHTML', false, 'your favourite component is...');",
  "SeaMonkey:Security": "Schneier would be proud...",
  "SeaMonkey:Preferences": "This might void your warranty...",
  "SeaMonkey:Testing Infrastructure": "TEST_UNEXPECTED_FAIL",
  "SeaMonkey:Installer": "Seamonkey will start in just a few moments...",
  "SeaMonkey:Feed Discovery and Preview": "Splitting the atom...",
  "SeaMonkey:General": "Sweet!",
  "SeaMonkey:Startup & Profiles": "In the beginning...",
  "SeaMonkey:MailNews: Message Display": "A sound of thunder...",
  "SeaMonkey:Project Organization": "",
  "SeaMonkey:UI Design": "Sweet!",
  "SeaMonkey:MailNews: Backend": "A sound of thunder...",
  "SeaMonkey:MailNews: Composition": "Dear sir...",
  "SeaMonkey:Themes": "I'm detecting a theme to your contributions...",
  "SeaMonkey:MailNews: Account Configuration": "Sweet!",
  "SeaMonkey:Build Config": "Making make do your bidding",
  "SeaMonkey:Autocomplete": "Remember when we had to type the same things over and over, like primitive beasts?",
  "SeaMonkey:Sync UI": "I feel like we're in sync...",
  "SeaMonkey:Help": "RTFM",
  "SeaMonkey:MailNews: Address Book & Contacts": "My only contact is nobody@mozilla.org. He never writes back.",
  "Mozilla Labs Graveyard:FlightDeck": "Igniting jetpack...",
  "Mozilla Labs:Chocolate Factory": "Someone's got ideas...",
  "Mozilla Labs:Ubiquity": "At your command...",
  "Mozilla Labs:Research": "",
  "Mozilla Labs:JS Modules": "",
  "Mozilla Labs:Test Pilot Studies": "Where did I put my goggles?",
  "Mozilla Labs:Personas": "I detect a theme to your contributions...",
  "Mozilla Labs:Test Pilot Data Requests": "You're embedded into Mozilla...",
  "Mozilla Labs:Jetpack SDK": "Igniting jetpack...",
  "Mozilla Labs:Gaming": "Achievement unlocked",
  "Mozilla Labs:Operator": "&lt; a rel='tag'&gt;Microformats&lt;/a&gt;",
  "Mozilla Labs:Identity": "No-one need ever be a persona non grata with your great work",
  "Mozilla Labs:Design": "Don't forget your lab coat...",
  "Mozilla Labs:OpenWebApps": "Apps everywhere",
  "Mozilla Labs:Joey": "The grandfather of 'Push Tab To Device'",
  "Mozilla Labs:Labs Pack": "Let me get my lab coat...",
  "Mozilla Labs:General": "Let me get my lab coat...",
  "Mozilla Labs:Concept Series": "Someone's got ideas...",
  "Mozilla Labs:New Tab": "I'm keeping tabs on you!",
  "Mozilla Labs:Test Pilot": "Where did I put my goggles?",
  "Mozilla Labs:Snowl": "Keeping the river of news flowing...",
  "Mozilla Labs:Prism": "Reflecting on web apps...",
  "Mozilla Labs:Raindrop": "Keeping track of the flamewars...",
  "Mozilla Labs:F1": "It's good to share...",
  "Mozilla Labs:Contacts": "",
  "Mozilla Labs:Doctor JS": "Analyse this...",
  "Mozilla Labs:Jetpack Prototype": "Igniting jetpack...",
  "Tracking:Kilimanjaro": "Climbing that mountain...",
  "CCK:CCK-Installation": "Suck it nerds - I'm going corporate!",
  "CCK:CCK-General": "Suck it nerds - I'm going corporate!",
  "CCK:CCK-Wizard": "Suck it nerds - I'm going corporate!",
  "Mozilla Grants:Reports/Deliverables": "I can haz grant?",
  "Mozilla Grants:Applications": "I can haz grant?",
  "Mozilla Grants:Administration/Accounting": "I can haz grant?",
  "Derivatives:Netscape 6": "NGLayout for the win...",
  "Petri:General": "Not just for cell cultures...",
  "Thimble:General": "Let's make the web!",
  "Pancake:Thumbnailer": "I'm looking for links on maple syrup...",
  "Pancake:Native iOS Wrapper": "Who needs Siri?",
  "Pancake:Front-end": "I'm looking for links on maple syrup...",
  "Pancake:Dashboard": "I'm looking for links on maple syrup...",
  "Pancake:General": "I'm looking for links on maple syrup...",
  "Pancake:Native Android Wrapper": "I'm looking for links on maple syrup...",
  "Pancake:Back-end": "I'm looking for links on maple syrup...",
  "Pancake:Add-On": "I'm looking for links on maple syrup...",
  "Pancake:Sync": "I'm looking for links on maple syrup...",
  "Mozilla Metrics:Metrics Operations": "Crunching the numbers. 100% awesome.",
  "Mozilla Metrics:Hadoop/HBase Operations": "Crunching the numbers. 100% awesome.",
  "Mozilla Metrics:downloadstats.mozilla.com": "Crunching the numbers. 100% awesome.",
  "Mozilla Metrics:Frontend Reports": "Crunching the numbers. 100% awesome.",
  "Mozilla Metrics:Metrics Data Ping": "Crunching the numbers. 100% awesome.",
  "Mozilla Metrics:Data/Backend Reports": "Crunching the numbers. 100% awesome.",
  "L20n:Evangelism": "You help put the 'world' in world-wide web. Awesome.",
  "L20n:General": "You help put the 'world' in world-wide web. Awesome.",
  "L20n:Python Library": "You help put the 'world' in world-wide web. Awesome.",
  "L20n:JS Library": "You help put the 'world' in world-wide web. Awesome.",
  "L20n:HTML Bindings": "You help put the 'world' in world-wide web. Awesome.",
  "Penelope:Compose Window": "J'adore eudora",
  "Penelope:Preferences": "This might void your warranty...",
  "Penelope:Mail Window": "J'adore eudora",
  "Penelope:Installer": "J'adore eudora",
  "Penelope:Help Documentation": "J'adore eudora",
  "Penelope:Filters": "J'adore eudora",
  "Penelope:General": "J'adore eudora",
  "Penelope:Toolbar": "J'adore eudora",
  "Penelope:Session Save/Restore": "J'adore eudora",
  "Community Tools:Phonebook": "Bringing the army of awesome closer together...",
  "Community Tools:TaskBoard": "Bringing the army of awesome closer together...",
  "Community Tools:Events Manager": "Bringing the army of awesome closer together...",
  "Finance:Purchase Request Form": "",
  "Finance:Vendor Amendment": "",
  "Finance:Offer Letter": "",
  "Finance:Accounting/Audit": "That Ferrari was a legitimate MoCo expense. Honest.",
  "Finance:Contractor Contract": "",
  "Finance:Bank Document": "",
  "Finance:Vendor SOW": "",
  "Mozilla Localizations:or / Oriya": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:is / Icelandic": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:bn-BD / Bengali": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ast / Asturian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ak / Akan": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:hu / Hungarian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:bs / Bosnian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:vi / Vietnamese": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ve / Venda": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:it / Italian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:hr / Croatian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ilo / Iloko": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:csb / Kashubian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ru / Russian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:th / Thai": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:lg / Luganda": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:rw / Kinyarwanda": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:nn-NO / Norwegian Nynorsk": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:nl / Dutch": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ka / Georgian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:sv-SE / Swedish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ne-NP / Nepali (Nepal)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:xh / Xhosa": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:he / Hebrew": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:gu-IN / Gujarati": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:es-MX / Spanish (Mexico)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ss / Swazi": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:sk / Slovak": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:gl / Galician": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:te / Telugu": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:kn / Kannada": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:MozillaTranslator": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:zu / Zulu": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:tn / Tswana": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:be / Belarusian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:rm / Romansh": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:lv / Latvian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:id / Indonesian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:my / Burmese": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:cs / Czech": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ga-IE / Irish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ach / Acholi": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:oc / Occitan": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ja / Japanese": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:nso / Northern Sotho (Pedi)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:fr / French": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:sl / Slovene": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:pa-IN / Punjabi": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ca / Catalan": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:sr / Serbian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:af / Afrikaans": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:st / Southern Sotho": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:en-ZA / English (South Africa)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:gd / Scottish Gaelic": "Slàinte mhòr!",
  "Mozilla Localizations:et / Estonian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:mr / Marathi": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:Registration & Management": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:en-GB / English (United Kingdom)": "The localisation where words are spelled correctly.",
  "Mozilla Localizations:ta / Tamil": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:fi / Finnish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:sw / Swahili": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ta-LK / Tamil (Sri Lanka)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:da / Danish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:lt / Lithuanian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ro / Romanian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:bg / Bulgarian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:cy / Welsh": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ms / Malay": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:mn / Mongolian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:es-AR / Spanish (Argentina)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:an / Aragonese": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:zh-TW / Chinese (Traditional)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:Infrastructure": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:mai / Maithili": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:pt-PT / Portuguese": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:eo / Esperanto": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:mk / Macedonian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:uk / Ukrainian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:pl / Polish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:el / Greek": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:lij / Ligurian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:eu / Basque": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ku / Kurdish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:km / Khmer": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:son / Songhay": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ts / Tsonga": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:hi-IN / hindi": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:pt-BR / Portuguese (Brazil)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:tr / Turkish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:Other": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:si / Sinhala": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:nr / Southern Ndebele": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ff / Fulah": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:hy-AM / Armenian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ko / Korean": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:sq / Albanian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:Documentation": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:zh-CN / Chinese (Simplified)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ur / Urdu": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ml / Malayalam": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:as / Assamese": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:es-ES / Spanish": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:es-CL / Spanish (Chile)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:br / Breton": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:fa / Persian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:fy-NL / Frisian": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:ar / Arabic": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:wo / Wolof": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:kk / Kazakh": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:de / German": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Localizations:bn-IN / Bengali (India)": "You help put the 'world' in world-wide web. Awesome.",
  "www.mozilla.org:Information Architecture & UX": "Mozilla's window to the world [wide web]",
  "www.mozilla.org:Legacy PHP system": "$LOLWUT?",
  "www.mozilla.org:L10N": "You help put the 'world' in world-wide web. Awesome.",
  "www.mozilla.org:Analytics": "Analyse this...",
  "www.mozilla.org:Project Tracking": "Mozilla's window to the world [wide web]",
  "www.mozilla.org:Pages & Content": "Mozilla's window to the world [wide web]",
  "www.mozilla.org:General": "Mozilla's window to the world [wide web]",
  "www.mozilla.org:Bedrock": "A fine looking foundation for Mozilla sites",
  "Snippets:Surveys": "Snip.",
  "Snippets:HTML5": "Snip.",
  "Snippets:General": "Snip.",
  "Snippets:Service": "Snip.",
  "Snippets:Campaign": "Snip.",
  "Firefox for Android:Data Providers": "",
  "Firefox for Android:Keyboards and IME": "Watch out for fat fingers!",
  "Firefox for Android:Download Manager": "I'm downloading more RAM right now...",
  "Firefox for Android:Plugins": "Additional plugins are required to view this content...",
  "Firefox for Android:General": "Who wants an ice-cream sandwich?",
  "Firefox for Android:Reader Mode": "Distilling the essence of a site...",
  "Firefox for Android:Readability": "body {font-size: xx-small;}",
  "Firefox for Android:Graphics, Panning and Zooming": "Desktop has it easy...",
  "Firefox for Android:JimDB": "Setting breakpoint...",
  "Firefox for Android:Evangelism": "Webkit isn't the only fruit",
  "Firefox for Android:Web Apps": "No lock-in here. This makes me 'appy",
  "Firefox for Android:Theme and Visual Design": "",
  "Firefox for Android:Add-on Manager": "Anything Desktop can do, we can do to...",
  "Firefox for Android:Text Selection": "Tap tap!",
  "Firefox for Android:Awesomescreen": "Because sometimes an awesomebar isn't enough",
  "webmaker.org:General": "Let's remix!",
  "Socorro:Infra": "Sending crash report...",
  "Socorro:Middleware": "Sending crash report...",
  "Socorro:Database": "Sending crash report...",
  "Socorro:Data request": "Sending crash report...",
  "Socorro:General": "Sending crash report...",
  "Socorro:Backend": "Sending crash report...",
  "Socorro:Webapp": "Sending crash report...",
  "Mozilla QA Graveyard:Mozmill Crowd Extension": "Mob mentality",
  "Mozilla QA Graveyard:Mozmill Result Dashboard": "Dash it!",
  "Testopia:Security": "Schneier would be proud",
  "Testopia:Fields": "Testing...",
  "Testopia:General": "Testing...",
  "Testopia:Cloning": "Testing...",
  "Testopia:Reports": "Testing...",
  "Testopia:API": "Testing...",
  "Testopia:User Interface": "Testing...",
  "Testopia:Test Plans": "Testing...",
  "Testopia:Import/Export": "Testing...",
  "Testopia:Search": "Testing...",
  "Testopia:Integrations": "Testing...",
  "Testopia:Test Runs": "Testing...",
  "Testopia:Test Cases": "Testing...",
  "Testopia:Tags": "Testing...",
  "Testopia:Environments": "Testing...",
  "quality.mozilla.org:Website": "No bugs here!",
  "quality.mozilla.org:Content": "No bugs here!",
  "Extend Firefox:General": "Build it and they will come. And extend it.",
  "Extend Firefox:Web Site": "Build it and they will come. And extend it.",
  "Calendar:Sunbird Only": "Save the date!",
  "Calendar:Provider: ICS/WebDAV": "BEGIN:VTODO SUMMARY: Rock the free web",
  "Calendar:Lightning: SeaMonkey Integration": "Save the date!",
  "Calendar:Calendar Views": "Save the date!",
  "Calendar:Alarms": "Save the date!",
  "Calendar:Provider: WCAP": "Save the date!",
  "Calendar:Dialogs": "Save the date!",
  "Calendar:OS Integration": "You've went native",
  "Calendar:Website": "Save the date!",
  "Calendar:Provider: CalDAV": "Save the date!",
  "Calendar:Printing": "PC LOAD LETTER",
  "Calendar:Tasks": "Save the date!",
  "Calendar:Import and Export": "Save the date!",
  "Calendar:Provider: GData": "Save the date!",
  "Calendar:Security": "Schneier would be proud",
  "Calendar:Preferences": "This might void your warranty...",
  "Calendar:E-mail based Scheduling (iTIP/iMIP)": "Save the date!",
  "Calendar:General": "Save the date!",
  "Calendar:Lightning Only": "Does it strike more than once?",
  "Calendar:Provider: Local Storage": "Save the date!",
  "Calendar:Internal Components": "Save the date!",
  "Calendar:Build Config": "Making make do your bidding",
  "Grendel:Preferences": "This might void your warranty...",
  "Grendel:Addressbook/LDAP (non-UI)": "",
  "Grendel:Protocols": "",
  "Grendel:User Interface": "",
  "mozillaignite:General": "",
  "JSS:Tests": "Schneier would be proud",
  "JSS:Documentation": "RTFM",
  "JSS:Sample Code": "Schneier would be proud",
  "JSS:Library": "Schneier would be proud",
  "Web Apps:HTML": "Apps everywhere!",
  "Web Apps:Soup": "Apps everywhere!",
  "Web Apps:Infrastructure": "Apps everywhere!",
  "Web Apps:Extension": "Apps everywhere!",
  "Web Apps:Dashboard": "Dash it!",
  "Web Apps:General": "Apps everywhere!",
  "Web Apps:AppsInTheCloud": "Head in the clouds...",
  "Webtools Graveyard:Party Tool": "The cake is a lie",
  "Webtools Graveyard:Download Day": "How many downloads :-o?",
  "Webtools Graveyard:Five Years of Firefox": "Back when we were young...",
  "Core:mach": "Considered harmless?",
  "Core:History: Global": "Those who can't remember the past...",
  "Core:Embedding: Mac": "You're embedded into Mozilla...",
  "Core:DOM: IndexedDB": "DROP TABLE object_store;",
  "Core:RDF": "I'm unsure of the semantics here...",
  "Core:Identity": "No-one need ever be a persona non grata with your great work",
  "Core:Widget": "You contribute to some gooey areas of code...",
  "Core:WebRTC: Networking": "Don't cross the streams!",
  "Core:DOM: Workers": "Deadlock detected!",
  "Core:js-ctypes": "function int_main(argc, argv) {",
  "Core:X-remote": "Remote control...",
  "Core:Plug-ins": "Are you some kind of masochist?",
  "Core:Layout: View Rendering": "You're in the frame for layout bugs",
  "Core:Security": "Also Alice and Bob's favourite component",
  "Core:Networking: JAR": "Did you like Binks in Episode I?",
  "Core:mozglue": "Some of your contributions seem linked...",
  "Core:Security: S/MIME": "Schneier would be proud",
  "Core:Preferences: Backend": "This might void your warranty...",
  "Core:Graphics: Layers": "You're like an onion. You've got layers",
  "Core:XPCOM": "QueryInterface(nsIYourFavouriteComponent)",
  "Core:Profile: Roaming": "Keeping a low profile...",
  "Core:SVG": "Look at the scale of your contributions...",
  "Core:XP Toolkit/Widgets: XUL": "Who ya gonna call?",
  "Core:DOM: Validation": "Invalid tag!",
  "Core:Hardware Abstraction Layer (HAL)": "You're contributions aren't so abstract!",
  "Core:Layout: Tables": "You're in the frame for layout bugs",
  "Core:Layout: Form Controls": "Where editors, frames and DOM trees collide. Oh my.",
  "Core:Find Backend": "Have you found what you're looking for?",
  "Core:Document Navigation": "Who's afraid of docshells and shistory? Not you.",
  "Core:Layout": "You're in the frame for layout bugs",
  "Core:Networking: HTTP": "404 Not found",
  "Core:Installer: XPInstall Engine": "Restart now?",
  "Core:DOM: Apps": "Apps everywhere",
  "Core:DOM: Mozilla Extensions": "Your contributions are non-standard",
  "Core:Networking: WebSockets": "Opening socket...",
  "Core:Networking: Cache": "Cache me if you can",
  "Core:HTML: Form Submission": "I submit to you that your favourite component is below...",
  "Core:Drag and Drop": "Coefficient of drag...",
  "Core:XML": "XML Parsing error: not well formed...just kidding",
  "Core:Widget: Android": "You contribute to some gooey areas of code...",
  "Core:Networking: Cookies": "White choc chip and macadamia nut, por favor",
  "Core:Layout: Misc Code": "You're in the frame for layout bugs",
  "Core:Widget: Cocoa": "Fancy a hot cup of cocoa?",
  "Core:WebDAV": "Let's collaborate!",
  "Core:Layout: Text": "Get those glyphs in place!",
  "Core:Graphics": "You like the azure skies above Cairo...",
  "Core:jemalloc": "My fragmented memory is trying to remember your favourite component...",
  "Core:WebRTC: Signaling": "Your favourite component is signalled below...",
  "Core:Networking": "Just following protocol...",
  "Core:Embedding: GRE Core": "You're embedded into Mozilla...",
  "Core:Tracking": "I'm watching you",
  "Core:DOM": "DOMException: NOT_SUPPORTED_ERR...haha, just kidding!",
  "Core:DOM: Other": "DOMException: NOT_SUPPORTED_ERR...haha, just kidding!",
  "Core:Web Services": "Sending SOAP request...",
  "Core:XBL": "One technology to bind them",
  "Core:Video/Audio": "Converting your result to ogv...",
  "Core:MathML": "Who needs Latex?",
  "Core:Networking: File": "",
  "Core:Java to XPCOM Bridge": "public static void QueryInterface...",
  "Core:XP Toolkit/Widgets: Menus": "",
  "Core:String": "AStrings and CStrings. Are we talking character classes or musical instruments? ",
  "Core:Serializers": "You're a serial contributor",
  "Core:Embedding: APIs": "You're embedded into Mozilla...",
  "Core:XTF": "Moar tags!",
  "Core:Widget: Gtk": "X marks the spot...",
  "Core:ImageLib": "Enabling animated GIFs since 1999",
  "Core:File Handling": "I'm going to mime the name of your top component",
  "Core:Print Preview": "Android? B2G? Hah. Dead trees. The real mobile web.",
  "Core:Embedding: Packaging": "You're embedded into Mozilla...",
  "Core:IPC": "Sending message...",
  "Core:Layout: Block and Inline": "Go with the flow...",
  "Core:Printing: Setup": "Android? B2G? Hah. Dead trees. The real mobile web.",
  "Core:XUL": "Who ya gonna call?",
  "Core:HTML: Parser": "Unexpected token. Entering quirks mode!",
  "Core:Security: UI": "Larry's monitoring you",
  "Core:Networking: DNS": "I can never get example.com to resolve",
  "Core:Widget: Win32": "Obtaining HWND...",
  "Core:Layout: HTML Frames": "Framesets are gonna make a comeback...",
  "Core:XForms": "Inputs for X-Men",
  "Core:Layout: Images": "Enabling animated GIFs since 1999...",
  "Core:Localization": "You help put the 'world' in world-wide web. Awesome.",
  "Core:WebRTC": "Don't cross the streams!",
  "Core:General": "You're hardcore!",
  "Core:JavaScript Engine": "Everybody's got something to hide except me and my monkey",
  "Core:Style System (CSS)": "display: none;",
  "Core:Printing: Output": "PC LOAD LETTER",
  "Core:DOM: Core & HTML": "DOMException: NOT_SUPPORTED_ERR...haha, just kidding!",
  "Core:Geolocation": "Where am I?",
  "Core:XPConnect": "You like the glue of the Mozilla universe. Also: sticky code.",
  "Core:Rewriting and Analysis": "Slaying bugs with the many hydrae.",
  "Core:Editor": "So you've got designs on contenteditable?",
  "Core:DOM: Device Interfaces": "Enabling bluetooth...",
  "Core:Image Blocking": "",
  "Core:Build Config": "Making make do your bidding",
  "Core:Embedding: MFC Embed": "You're embedded into Mozilla...",
  "Core:Widget: Gonk": "You contribute to some gooey areas of code...",
  "Core:Nanojit": "Compiling...",
  "Core:MFBT": "What time is it?",
  "Core:Event Handling": "Well this is quite the event...",
  "Core:Layout: R & A Pos": "Everything's relative. Unless we're dealing with absolutes.",
  "Core:Profile: BackEnd": "Keeping a low profile...",
  "Core:Widget: Qt": "You contribute to some gooey areas of code...",
  "Core:Spelling checker": "Teh lousy typist's best friend",
  "Core:Selection": "The component you selected is...",
  "Core:Canvas: 2D": "The web is your canvas...",
  "Core:Disability Access APIs": "",
  "Core:Security: PSM": "Schneier would be prpud",
  "Core:QuickLaunch (AKA turbo mode)": "You feel the need for speed",
  "Core:Internationalization": "You help put the 'world' in world-wide web. Awesome.",
  "Core:Gecko Profiler": "Hitting the hotspots...",
  "Core:GFX: Color Management": "Only available in black...",
  "Core:SQL": "DROP ALL TABLES;",
  "Core:DOM: Traversal-Range": "Calculating boundary point...",
  "Core:Keyboard: Navigation": "No mice infestation here",
  "Core:WebRTC: Audio/Video": "Don't cross the streams...",
  "Core:Networking: Domain Lists": "Updating public suffix list...",
  "Core:Profile: Migration": "TODO: Delete their copies of IE and Chrome after you've migrated their data",
  "Core:Canvas: WebGL": "I'm blacklisting your graphics card...",
  "Core:Widget: Photon": "You contribute to some gooey areas of code...",
  "Core:Widget: BeOS": "You contribute to some gooey areas of code...",
  "Core:Graphics: Text": "Decoding the glyphs...",
  "Core:XSLT": "Transforming...",
  "Core:Networking: FTP": "Entering passive mode...",
  "Core:Widget: OS/2": "You contribute to some gooey areas of code...",
  "Core:DOM: CSS Object Model": "Generating CSSRuleList...",
  "Core:Security: CAPS": "Say what you like, I think enablePrivelege is going to come back in fashion",
  "Core:DOM: Events": "Well this is quite the event...",
  "Core:Layout: Floats": "You don't go with the flow",
  "Mozilla Reps:Planning": "Spreading the word...",
  "Mozilla Reps:Add-on": "Spreading the word...",
  "Mozilla Reps:Swag Requests": "Who wants swag? Everybody!",
  "Mozilla Reps:Budget Requests": "Spreading the word...",
  "Mozilla Reps:reps.mozilla.org": "Spreading the word...",
  "Mozilla Reps:Mentorship": "Spreading the word...",
  "Mozilla Reps:Community IT Requests": "Spreading the word...",
  "NSS:Libraries": "Schneier would be proud",
  "NSS:Build": "Schneier would be proud",
  "NSS:CA Certificates": "Schneier would be proud",
  "NSS:Tools": "Schneier would be proud",
  "NSS:Test": "Schneier would be proud",
  "NSS:Documentation": "Schneier would be proud",
  "Core Graveyard:Viewer App": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: OS/2": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Java APIs to WebShell": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: Xlib": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Printing: Xprint": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Cmd-line Features": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: Win32": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Talkback Client": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: Mac": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Installer: MFCEmbed": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: Gtk": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Ports: Qt": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Widget: Xlib": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:QuickLaunch (AKA turbo mode)": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:View Source": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Java-Implemented Plugins": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Embedding: ActiveX Wrapper": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Java: OJI": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Image: Painting": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Java: Live Connect": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Embedding: GTK Widget": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: BeOS": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Widget: Mac": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Error Console": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Installer: GRE": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Skinability": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:Java APIs for DOM": "Ah, retro Mozilla. You hipster.",
  "Core Graveyard:GFX: Photon": "Ah, retro Mozilla. You hipster.",
  "MailNews Core:Networking: POP": "Cheque's in the post...",
  "MailNews Core:Attachments": "You're attached to Mozilla, aren't you?",
  "MailNews Core:Networking: NNTP": "All the news that's fit to print",
  "MailNews Core:Simple MAPI": "Calling MAPIFreeBuffer",
  "MailNews Core:Search": "Have you found what you're looking for?",
  "MailNews Core:Movemail": "Moving mail...",
  "MailNews Core:LDAP Integration": "Binding to session...",
  "MailNews Core:Printing": "PC LOAD LETTER",
  "MailNews Core:Internationalization": "You help put the 'world' in world-wide web. Awesome.",
  "MailNews Core:Composition": "Dear sir...",
  "MailNews Core:Security": "Schneier would be proud",
  "MailNews Core:MIME": "Detecting content-type...",
  "MailNews Core:Networking": "Just following protocol",
  "MailNews Core:Testing Infrastructure": "TEST_UNEXPECTED_FAIL",
  "MailNews Core:Database": "DROP TABLE messages;",
  "MailNews Core:Feed Reader": "Splitting the atom",
  "MailNews Core:Security: S/MIME": "Schneier would be proud",
  "MailNews Core:Profile Migration": "TODO: Delete their copy of Outlook after you've migrated their data",
  "MailNews Core:Localization": "You help put the 'world' in world-wide web. Awesome.",
  "MailNews Core:Networking: IMAP": "Following protocol...",
  "MailNews Core:Import": "Importing messages...",
  "MailNews Core:Networking: SMTP": "Following protocol...",
  "MailNews Core:Address Book": "My only contact is nobody@mozilla.org. He never writes back.",
  "MailNews Core:Filters": "Why do you keep filtering those Nigerian prince emails I keep sending you :(",
  "MailNews Core:Build Config": "Making make do your bidding",
  "MailNews Core:Backend": "You've got mail...",
  "MailNews Core:Account Manager": "Switching accounts...",
  "Toolkit:Password Manager": "I hope your password isn't 'password'!",
  "Toolkit:Application Update": "Ship it!",
  "Toolkit:Spatial Navigation": "",
  "Toolkit:Startup and Profile System": "In the beginning...",
  "Toolkit:about:memory": "Watch out for dark matter!",
  "Toolkit:XULRunner": "Who needs a browser?",
  "Toolkit:Toolbars and Toolbar Customization": "Let's add more buttons!",
  "Toolkit:Places": "I tell you, that awesomebar idea is going places...",
  "Toolkit:XUL Widgets": "The LEGO bricks of Mozilla UI...",
  "Toolkit:Telemetry": "Accumulating data...",
  "Toolkit:Printing": "Android? B2G? Hah. Dead trees. The real mobile web.",
  "Toolkit:Breakpad Integration": "Sending crash report...",
  "Toolkit:View Source": "Hopefully not generated by Microsoft FrontPage...",
  "Toolkit:Security": "Schneier would be proud",
  "Toolkit:Preferences": "This might void your warranty...",
  "Toolkit:Download Manager": "I'm downloading more RAM right now...",
  "Toolkit:Find Toolbar": "I still haven't found what I'm looking for...",
  "Toolkit:Microformats": "Splitting the atom...",
  "Toolkit:General": "What's in your toolbox?",
  "Toolkit:Add-ons Manager": "Build it, and they will come. And extend it.",
  "Toolkit:Video/Audio Controls": "Turn up the volume! And, er, the video.",
  "Toolkit:Help Viewer": "RTFM",
  "Toolkit:OS.File": "rm -rf *",
  "Toolkit:Error Console": "consoleService.logStringMessage('You're favourite component');",
  "Toolkit:NSIS Installer": "Welcome to the Firefox setup wizard...",
  "Toolkit:Themes": "I'm detecting a theme here...",
  "Toolkit:Storage": "Upgrading SQLite...",
  "Toolkit:Plugin Finder Service": "Additional plugins are required to view this content...",
  "Toolkit:Form Manager": "What's in your satchel?",
  "Toolkit:Build Config": "Making make do your bidding",
  "Toolkit:Autocomplete": "Remember when we had to type the same things over and over, like primitive beasts?",
  "Tech Evangelism:French": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Greek": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Punjabi": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Lithuanian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Kannada": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Frisian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Georgian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Maithili": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Bengali": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:German": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Romanian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Thai": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Irish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Persian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Welsh": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Vietnamese": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Polish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Turkish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Croatian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Hungarian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Armenian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Basque": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Czech": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Songhai": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Albanian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Macedonian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Bulgarian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Mobile": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Latvian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Zulu": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Russian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Norwegian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:English Other": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Malayalam": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Portuguese": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Romansh": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Scottish-Gaelic": "Slàinte mhòr!",
  "Tech Evangelism:Hindi": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Swedish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Arabic": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Danish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Esperanto": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Ukrainian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Slovak": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Estonian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Hebrew": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Indonesian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Telugu": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Korean": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Mongolian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Breton": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Slovenian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Spanish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Gujarati": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Japanese": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Chinese-Simplified": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Bosnian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Afrikaans": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Icelandic": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Finnish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Kazakh": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Other": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Catalan": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Asturian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:English US": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Marathi": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Akan": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Tamil": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Chinese-Traditional": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Dutch": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Sinhala": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Add-ons": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Kurdish": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Assamese": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Luganda": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Oriya": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Serbian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Belarusian": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Galician": "You help put the 'world' in world-wide web. Awesome.",
  "Tech Evangelism:Italian": "You help put the 'world' in world-wide web. Awesome.",
  "Rhino:E4X": "Rhinos > monkeys",
  "Rhino:Compiler": "Rhinos > monkeys",
  "Rhino:Core": "Rhinos > monkeys",
  "AUS:Systems": "Keep those trains running...",
  "AUS:General": "Keep those trains running...",
  "AUS:API": "Keep those trains running...",
  "AUS:Administration": "Keep those trains running...",
  "MozillaClassic:Layout": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Berkeley DB": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Java Stubs": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:HTMLtoText/PostScript Trans": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:FontLib": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Windows FE": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:PICS": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Browser Hooks": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:PNG Image Handling": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Aurora/RDF BE": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Composer": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Security Stubs": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Preferences": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Calendar": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Macintosh FE": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Registry": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:LibMocha": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:XFE": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Compositor Library": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:MIMELib": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:StubFE": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:Aurora/RDF FE": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:NetLib": "Ah, retro Mozilla. You hipster.",
  "MozillaClassic:JPEG Image Handling": "Ah, retro Mozilla. You hipster.",
  "Skywriter:Server": "As used by the coders in Cloud City",
  "Skywriter:File Explorer": "As used by the coders in Cloud City",
  "Skywriter:Add-ons & Plugins": "As used by the coders in Cloud City",
  "Skywriter:Thunderhead": "As used by the coders in Cloud City",
  "Skywriter:Command Line": "As used by the coders in Cloud City",
  "Skywriter:Search": "As used by the coders in Cloud City",
  "Skywriter:Infrastructure": "As used by the coders in Cloud City",
  "Skywriter:Version Control": "As used by the coders in Cloud City",
  "Skywriter:Embedded": "As used by the coders in Cloud City",
  "Skywriter:Documentation": "RTFM",
  "Skywriter:General": "As used by the coders in Cloud City",
  "Skywriter:Syntax Highlighting": "As used by the coders in Cloud City",
  "Skywriter:User Interface": "As used by the coders in Cloud City",
  "Skywriter:Key Bindings": "As used by the coders in Cloud City",
  "Skywriter:Collaboration": "Let's collaborate!",
  "Skywriter:Editor": "As used by the coders in Cloud City",
  "Composer:Startup": "In the beginning...",
  "Composer:Templates": "",
  "Composer:Tabbed Editor": "",
  "Composer:OS Integration": "You've went native...",
  "Composer:Colorpicker": "Only available in black",
  "Composer:Source View": "",
  "Composer:CSS Styles": "display: none;",
  "Composer:Site Manager": "",
  "Composer:Tabs": "I'm keeping tabs on you...",
  "Composer:Preferences": "This might void your warranty...",
  "Composer:Sidebars": "Can I take you aside?",
  "Composer:Installer": "Seamonkey will start in just a few moments...",
  "Composer:Toolbars": "",
  "Composer:Documentation": "RTFM",
  "Composer:Extensions and Themes": "Build it and they will come. And extend it.",
  "Composer:General": "Compose yourself!",
  "Composer:Accessibility": "",
  "Composer:Tip of the Day": "Today's tip: IE6 will make a glorious comeback, you wait and see!",
  "Composer:Build Config": "Making make do your bidding",
  "Composer:CSS Editor": "display: none;",
  "Composer:Software Update": "",
  "Thunderbird:Toolbars and Tabs": "I'm keeping tabs on you...",
  "Thunderbird:FileLink": "A sound of thunder...",
  "Thunderbird:Untriaged": "",
  "Thunderbird:Message Compose Window": "Dear sir...",
  "Thunderbird:Instant Messaging": "LOL OMG ROFL",
  "Thunderbird:OS Integration": "You've went native...",
  "Thunderbird:Theme": "I'm detecting a theme here...",
  "Thunderbird:Folder and Message Lists": "A sound of thunder...",
  "Thunderbird:Search": "Have you found what you're looking for?",
  "Thunderbird:Security": "Schneier would be proud...",
  "Thunderbird:Preferences": "This might void your warranty...",
  "Thunderbird:Testing Infrastructure": "A sound of thunder...",
  "Thunderbird:Installer": "Thunderbird will start in just a few moments...",
  "Thunderbird:Migration": "TODO: Delete their copy of Outlook after you've migrated their data",
  "Thunderbird:Disability Access": "A sound of thunder...",
  "Thunderbird:General": "A sound of thunder...",
  "Thunderbird:Message Reader UI": "A sound of thunder...",
  "Thunderbird:Mail Window Front End": "A sound of thunder...",
  "Thunderbird:Address Book": "My only contact is nobody@mozilla.org. He never writes back.",
  "Thunderbird:Filters": "Tag those Nigerian 419 scams as important",
  "Thunderbird:Help Documentation": "RTFM",
  "Thunderbird:Build Config": "Making make do your bidding...",
  "Thunderbird:Account Manager": "A sound of thunder...",
  "Add-on SDK:General": "Igniting jetpack...",
  "Add-on SDK:Documentation": "RTFM",
  "support.mozillamessaging.com:Knowledge Base Articles": "RTFM",
  "support.mozillamessaging.com:General": "RTFM",
  "Marketing:Business Development": "",
  "Marketing:Video": "Spread the word!",
  "Marketing:Copy": "All the Mozilla news that's fit to print...",
  "Marketing:Swag Requests": "Mmm, swag!",
  "Marketing:General": "Spread the word!",
  "Marketing:Social Media": "Spread the word!",
  "Marketing:Event Requests": "Spread the word!",
  "Marketing:Trademark Violations": "Bad news. Apple patented the Mozilla wordmark. And they're ready to sue...",
  "Marketing:Design": "Spread the word!",
  "Marketing:Email": "Spread the word!",
  "Marketing:Trademark Permissions": "Bad news. Apple patented the Mozilla wordmark. And they're ready to sue...",
  "Websites:www.seamonkey-project.org": "Sweet!",
  "Websites:planet.firefox.com/mobile": "All the news that's fit to print",
  "Websites:downloadstats.mozilla.com": "How many downloads? :-o",
  "Websites:blog.mozilla.com/theden": "",
  "Websites:intlstore.mozilla.org": "Who wants swag? Everybody!",
  "Websites:donate.mozilla.org": "Do you accept BitCoin?",
  "Websites:www.mozilla-japan.org": "Firefox-san!",
  "Websites:Webtrends": "Analyse this...",
  "Websites:extendfirefox.com/mobile-cup/": "",
  "Websites:spreadthunderbird.com": "Spread the word!",
  "Websites:studentreps.mozilla.org": "Spread the word!",
  "Websites:plugins.mozilla.org": "Additional plugins are required to view this content...",
  "Websites:mozilla.status.net": "Unable to connect to www.mozilla.org!",
  "Websites:Betafarm": "It's like a science fair!",
  "Websites:planet.mozilla.org": "All the news that's fit to print",
  "Websites:tools.mozilla.com": "",
  "Websites:mozilla.org.uk": "Where the free web meets Earl Gray",
  "Websites:firefoxgarden.org": "How does your garden grow?",
  "Websites:www.mozilla.org/thunderbird": "A sound of thunder...",
  "Websites:www.mozilla-europe.org": "Spreading Mozilla across the EU...",
  "Websites:blog.mozilla.org": "All the news that's fit to print",
  "Websites:webifyme.org": "What does your web look like?",
  "Websites:openbadges.org": "Achievement unlocked!",
  "Websites:markup.mozilla.org": "This ain't no graffiti!",
  "Websites:mozillalabs.com": "Where did I put my lab coat?",
  "Websites:getfirebug.com": "The web developer's best friend",
  "Websites:browserchoice.mozilla.com": "I hope you chose Firefox!",
  "Websites:Firefox Start": "",
  "Websites:www.drumbeat.org": "Banging the drum...",
  "Websites:feeds.mozilla.com": "",
  "Websites:Firefox Flicks": "TODO: Out-gross 'The Dark Knight Rises' at the box-office",
  "Websites:www.mozilla.jp": "Firefox-san!",
  "Websites:store.mozilla.org": "Mmm. Swag.",
  "Websites:detodosparatodos.org": "Spreading the word!",
  "Websites:workshop.mozilla.org": "",
  "Websites:air.mozilla.com": "From Mountain View to the world...",
  "Websites:communitystore.mozilla.org": "Who wants swag? Everybody!",
  "Websites:other.mozilla.org": "",
  "Websites:byob.mozilla.com": "If you build it, they will come. And build their own.",
  "Websites:wiki.mozilla.org": "I reverted your edits as vandalism",
  "Websites:demos.mozilla.org": "Show-off!",
  "Websites:www.mozillaonline.com": "Spreading the red panda in the Middle Kingdom...",
  "Websites:Other": "",
  "Websites:hacks.mozilla.org": "Show-off!",
  "Websites:Facebook": "450 million people liked this",
  "Websites:learningfreedomandtheweb.org": "",
  "Websites:getpersonas.com": "Does it come in yellow?",
  "Websites:Your Web": "",
  "Websites:creative.mozilla.org": "Let's get creative!",
  "Websites:bespinplugins.mozillalabs.com": "As used by the coders in Cloud City",
  "Websites:spark.mozilla.org": "Spread the word!",
  "Websites:etherpad.mozilla.org": "Let's collaborate!",
  "Websites:Web Analytics": "Analyse this...",
  "Websites:website-archive.mozilla.org": "Gone, but not forgotten",
  "Websites:glow.mozilla.org": "How many downloads? :-o",
  "Websites:Scrumbugs": "Sprinting to the finish line...",
  "Websites:BrowserQuest": "Old-school RPGs are alive and kicking...",
  "Websites:Mozilla Community Sites": "Spread the word!",
  "Documentation:Web Developer": "RTFM",
  "Documentation:PRD Change Request": "RTFM",
  "Documentation:Help Viewer": "RTFM",
  "Popcorn:Popcorn.js": "Salted or sweet?",
  "Popcorn:Popcorn Maker": "Salted or sweet?",
  "Mozilla Developer Network:Tags / flags": "",
  "Mozilla Developer Network:File attachments": "You're attached to MDN...",
  "Mozilla Developer Network:Demo Studio / Dev Derby": "Like Aperture Science, doing things because we can!",
  "Mozilla Developer Network:Login": "What's your persona?",
  "Mozilla Developer Network:API": "",
  "Mozilla Developer Network:Administration": "Hooray for Kuma!",
  "Mozilla Developer Network:User management": "Hooray for Kuma!",
  "Mozilla Developer Network:Other": "Hooray for Kuma!",
  "Mozilla Developer Network:Website": "302 w3schools.com :-P",
  "Mozilla Developer Network:SEO": "302 w3schools.com :-P",
  "Mozilla Developer Network:KumaScript": "302 w3schools.com :-P",
  "Mozilla Developer Network:Landing pages": "302 w3schools.com :-P",
  "Mozilla Developer Network:Demos": "Like Aperture Science, doing things because we can!",
  "Mozilla Developer Network:Site search": "302 w3schools.com :-P",
  "Mozilla Developer Network:Security": "302 w3schools.com :-P",
  "Mozilla Developer Network:Editing": "302 w3schools.com :-P",
  "Mozilla Developer Network:Localization": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Developer Network:Documentation": "302 w3schools.com :-P",
  "Mozilla Developer Network:User profiles": "302 w3schools.com :-P",
  "Mozilla Developer Network:Design / user experience": "302 w3schools.com :-P",
  "Mozilla Developer Network:Performance": "",
  "Mozilla Developer Network:Dashboards": "Dash it!",
  "Mozilla Developer Network:Collaboration": "Let's collaborate!",
  "Mozilla Developer Network:Docs Platform": "302 w3schools.com :-P",
  "Mozilla Communities:es-MX / Spanish (Mexico)": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Communities:sk / Slovak": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Communities:Philippines": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Communities:Contributor Engagement": "Growing the army of awesome",
  "Mozilla Communities:de / German": "You help put the 'world' in world-wide web. Awesome.",
  "Mozilla Communities:cs / Czech": "You help put the 'world' in world-wide web. Awesome.",
  "Privacy:Privacy Review": "Don't be evil!",
  "Privacy:Privacy Policies": "Don't be evil!",
  "Privacy:Vendor Review": "Don't be evil!",
  "Privacy:General": "Don't be evil!",
  "Privacy:Data Release Proposal": "Don't be evil!",
  "Tamarin:ScreamingMonkey": "So many monkeys...",
  "Tamarin:Garbage Collection (mmGC)": "",
  "Tamarin:Optimizing JIT": "",
  "Tamarin:Library": "",
  "Tamarin:API": "",
  "Tamarin:Workers": "",
  "Tamarin:Tracing Virtual Machine": "",
  "Tamarin:Interpreter": "",
  "Tamarin:Tools": "",
  "Tamarin:Self-hosting compiler (ESC)": "",
  "Tamarin:Virtual Machine": "",
  "Tamarin:Debugger": "",
  "Tamarin:Documentation": "",
  "Tamarin:Baseline JIT (CodegenLIR)": "",
  "Tamarin:Verifier": "",
  "Tamarin:Profiler": "Hitting the hotspots...",
  "Tamarin:Build Config": "",
  "Fennec:Shell Integration": "You've went native...",
  "Fennec:Panning/Zooming": "Desktop has it easy...",
  "Fennec:General": "Anything desktop can do, we can do better...",
  "Fennec:Extension Compatibility": "&lt;em:maxversion&gt;Firebird 0.5&lt;em:maxversion&gt;",
  "Fennec:Theme": "I'm detecting a theme here...",
  "Fennec:Bookmarks": "Will you bookmark this page?"
};
